---
title: "Model Outputs"
output: html_notebook
---
# Load Packages
```{r}
library(tidycensus)
library(tidyverse)
library(sf)
library(sjPlot)
library(sjmisc)
library(stargazer)
library(lme4)
library(lmerTest)
library(sjPlot)
library(sjmisc)
library(ggplot2)

library(ggeffects)
library(performance)
library(jtools)
library(R2MLwiN)
library(lmtest)
## Change path to MLwiN executable as appropriate:
options(MLwiN_path="/Users/shivyucel/Documents/projects/DPhil/Code_Data/mlwin/mlnscript")
```


# Load/Prepare Data

```{r}
# v12 is full model variables
#v17 is new demographic + popdens
mob_vars <- st_read("/Users/shivyucel/Documents/projects/DPhil/Code_Data/data/mobility_heat/mobility_heat_dataset_update.csv")

#set up dependent variables
mob_vars$residential_difference <- as.numeric(mob_vars$residential_difference)
mob_vars$workplaces_difference <- as.numeric(mob_vars$workplaces_difference)
mob_vars$grocery_pharmacy_difference <- as.numeric(mob_vars$grocery_pharmacy_difference)
mob_vars$parks_difference <- as.numeric(mob_vars$parks_difference)
mob_vars$retail_difference <- as.numeric(mob_vars$retail_difference)
mob_vars$transit_difference <- as.numeric(mob_vars$transit_difference)


#set up independent variables

#level 1 variables
mob_vars$heat_temp_centered <- as.numeric(mob_vars$heat_temp_centered)
mob_vars$temp_diff <- as.numeric(mob_vars$temp_diff)

mob_vars$stage_frac <- as.numeric(mob_vars$stage_frac) / 100
mob_vars$weekend <- as.factor(mob_vars$weekend)

#level 2 variables

mob_vars$june_hw <- as.factor(mob_vars$june_hw)
mob_vars$heatwave_dur <- as.factor(mob_vars$heatwave_dur)
mob_vars$year <- as.factor(mob_vars$year)


#level 3 variables

#centre winter temperature for interaction term
mob_vars$temperature_2m_winter <- as.numeric(mob_vars$temperature_2m_winter) - 4

mob_vars$state <- as.factor(mob_vars$state)
mob_vars$state <- relevel(factor(mob_vars$state), "California")
mob_vars$coast_binary <- as.factor(mob_vars$coast_binary)
mob_vars$temperature_2m_heat <- as.numeric(mob_vars$temperature_2m_heat)
mob_vars$income_dec <- as.numeric(mob_vars$income_dec)

mob_vars$over65_dec <-  as.numeric(mob_vars$over65_dec)
mob_vars$popdens_dec <-  as.numeric(mob_vars$popdens_dec)
mob_vars$nonwhite_dec <-  as.numeric(mob_vars$nonwhite_dec)
```

# Unconditional Means

```{r}
model_24 <- runMLwiN(c(residential_difference, workplaces_difference, transit_difference, grocery_pharmacy_difference, retail_difference, parks_difference) ~ 1 +
                    + (1 | location) + ( 1| heat_ID) + (1|index),
                    data = mob_vars, D = "Multivariate Normal", estoptions = list(sort.ignore=TRUE, resi.store=TRUE) )
```


```{r}
model_24
```


## Full Model


```{r}

model_26 <- runMLwiN(c(residential_difference, workplaces_difference, transit_difference, grocery_pharmacy_difference, retail_difference, parks_difference) ~ 1 
                    + heat_temp_centered*state + temp_diff + stage_frac  + weekend 
                    + factor(year) + factor(heatwave_dur) + factor(june_hw)
                    + factor(coast_binary) +  temperature_2m_winter:state + popdens_dec + income_dec + over65_dec + nonwhite_dec 
                    +   (1 | location) + ( 1| heat_ID) + (1|index), 
                    data = mob_vars, D = "Multivariate Normal", estoptions = list(sort.force=TRUE, resi.store=TRUE, maxiter = 30))

```




```{r}
summary(model_26)

```


```{r}
# save coefficients
x <- data.frame(model_26@FP)

write.csv(x, file='/Users/shivyucel/Documents/projects/DPhil/Code_Data/data/regression/update_params_clean_final_90_v1.csv')
```


